# Generated by Django 5.0.3 on 2025-06-26 02:27

from django.db import migrations, models

# Conditional import for backward compatibility
try:
    import tinymce.models
except ImportError:
    # Create a fallback HTMLField for migration compatibility
    from django.db import models as django_models
    class HTMLField(django_models.TextField):
        pass
    class MockTinyMCE:
        models = type('models', (), {'HTMLField': HTMLField})
    import sys
    sys.modules['tinymce'] = MockTinyMCE()
    sys.modules['tinymce.models'] = MockTinyMCE.models
    tinymce = MockTinyMCE()
    tinymce.models = MockTinyMCE.models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="editor_session_id",
            field=models.CharField(
                blank=True,
                help_text="Current editor session identifier",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="is_auto_saving",
            field=models.BooleanField(
                default=False, help_text="Indicates if auto-save is in progress"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="last_saved_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last auto-save timestamp"
            ),
        ),
        migrations.AddField(
            model_name="articletranslation",
            name="draft_content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Draft content that may differ from published content",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                through="content.ArticleTag",
                to="content.tag",
            ),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Published article content (HTML)"
            ),
        ),
    ]
