# Generated by Django 5.0.3 on 2025-06-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_article_editor_session_id_article_is_auto_saving_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articletranslation",
            name="content",
            field=models.TextField(help_text="Published article content (HTML)"),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="draft_content",
            field=models.TextField(
                blank=True,
                help_text="Draft content that may differ from published content",
                null=True,
            ),
        ),
    ]
