# Generated by Django 5.0.3 on 2025-06-26 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0002_initial"),
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                help_text="User who bookmarked the article",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                help_text="Article this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="content.article",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="Comment author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for threaded comments",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="interactions.comment",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="article",
            field=models.ForeignKey(
                help_text="Article that was liked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="content.article",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                help_text="User who liked the article",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("article", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("article", "user")},
        ),
    ]
